/**
 * gestion de stock REST API
 * gestion de stock api documentation
 *
 * The version of the OpenAPI document: 1.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Adresse } from './adresse';


export interface ClientDto { 
    id?: number;
    nom?: string;
    prenom?: string;
    adresse?: Adresse;
    photo?: string;
    mail?: string;
    numTel?: string;
    idEntreprise?: number;
}

