/**
 * gestion de stock REST API
 * gestion de stock api documentation
 *
 * The version of the OpenAPI document: 1.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EntrepriseDto {
    adresse: import("c:/Users/alaah/Desktop/gestiondestock/frontend-gs/src/gs-api/src/index").Adresse; 
    id?: number;
    name?: string;
    description?: string;
    codeFiscal?: string;
    photo?: string;
    mail?: string;
    numTel?: string;
    idEntreprise?: number;
}

